.TH BIGFILES 1 "v\ 1.0.0" "Mon, May 12, 2014" "GNU"
.SH NAME
.B bigfiles
\- list files recursively in given directory in order of biggest to smallest.
.SH SYNOPSIS
bigfiles directory
.br
bigfiles -h
.br
.SH OPTIONS
-h Prints help information.
.SH DESCRIPTION

.br
.SH BUGS
Does not handle dirs with embedded "'".
.SH VERSION
This documentation describes
.B bigfiles
version 1.0.0
.SH "SEE ALSO"
duplicates(1), brokensym(1)
.br
.SH AUTHOR
.br
.B Bob Parker
.br
.I \<\>
